### ISSUE TITLE
Installation cleaning ERROR 1

### ISSUE THREAD

**Issue by darkmorpher** [kanzure/pdfparanoia#48]
```
C:\Users\ex>pip install pdfparanoia
Collecting pdfparanoia
  Downloading pdfparanoia-0.0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ex\appdata\local\temp\pip-build-ftnxqw\pdfparanoia\setup.py", line 6, in <module>
        import pdfparanoia
      File "c:\users\ex\appdata\local\temp\pip-build-ftnxqw\pdfparanoia\pdfparanoi\__init__.py", line 27, in <module>
        from .core import scrub
      File "c:\users\ex\appdata\local\temp\pip-build-ftnxqw\pdfparanoia\pdfparanoia\core.py", line 13, in <module>
        from .parser import (
      File "c:\users\ex\appdata\local\temp\pip-build-ftnxqw\pdfparanoia\pdfparanoi\parser.py", line 18, in <module>
        import pdfminer.pdfparser
    ImportError: No module named pdfminer.pdfparser

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\ex\appdata\local\temp\pip-build-ftnxqw\pdfparanoia
```

**Comment by kanzure** [comment]
Could you try with `pip3` by any chance?

**Comment by darkmorpher** [comment]
pip 8.0.2 on python 2.7
