### ISSUE TITLE
Why i meet a byte problem

### ISSUE THREAD

**Issue by jilinsunkun** [kanzure/pdfparanoia#52]
what do I mean by string
```
C:\Users\dell\Desktop\水印删除>C:\Users\dell\Desktop\水印删除\pdf-watermark-removal.py
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\水印删除\pdf-watermark-removal.py", line 3, in <module>
    pdf = pdfparanoia.scrub(open("天勤2019数据结构计算机考研复习指导电子版PDF.pdf", "rb"))
  File "D:\ProgramData\Anaconda3\lib\site-packages\pdfparanoia-0.0.16-py3.6.egg\pdfparanoia\core.py", line 53, in scrub
    content = plugin.scrub(content, verbose=verbose)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pdfparanoia-0.0.16-py3.6.egg\pdfparanoia\plugins\aip.py", line 25, in scrub
    pdf = parse_content(content)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pdfparanoia-0.0.16-py3.6.egg\pdfparanoia\parser.py", line 44, in parse_content
    stream = StringIO(content)
TypeError: initial_value must be str or None, not bytes``
```

**Comment by carlcrott** [comment]
Could you provide a link to the file you're parsing?

**Comment by jilinsunkun** [comment]
The origin file is too big to upload,So I change a file , and i think it may not change...
`Traceback (most recent call last):
  File "C:\Users\dell\Desktop\水印删除\pdf-watermark-removal.py", line 3, in <module>
    pdf = pdfparanoia.scrub(open("document.pdf", "rb"))
  File "D:\ProgramData\Anaconda3\lib\site-packages\pdfparanoia-0.0.16-py3.6.egg\pdfparanoia\core.py", line 53, in scrub
    content = plugin.scrub(content, verbose=verbose)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pdfparanoia-0.0.16-py3.6.egg\pdfparanoia\plugins\aip.py", line 25, in scrub
    pdf = parse_content(content)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pdfparanoia-0.0.16-py3.6.egg\pdfparanoia\parser.py", line 44, in parse_content
    stream = StringIO(content)
TypeError: initial_value must be str or None, not 

- 

- bytes`


[document.pdf](https://github.com/kanzure/pdfparanoia/files/3077516/document.pdf)

**Comment by udayhasan** [comment]
I'm facing a similar issue. Can anyone help?
Or, did any of you found any workaround?

**Comment by fanshao** [comment]
I'm facing a similar issue.

**Comment by slarrain** [comment]
Similar issue

**Comment by sylph520** [comment]
similar here.

**Comment by seanbenhur** [comment]
Oh, similar here
