### ISSUE TITLE
can not  install in win10 with python 3.9:pip install pdfparanoia

### ISSUE THREAD

**Issue by ghost** [kanzure/pdfparanoia#55]
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by BaqirHassan** [comment]
just open the readme.MD in your favorite text editor and del the second paragraph. It is in some language other than English which is not understood by python.

And please let me know if the project runs for you.
Email: baqirhassan008@gmail.com

thanks for your time.

**Comment by kanzure** [comment]
Windows doesn't have unicode?

**Comment by BaqirHassan** [comment]
> Windows doesn't have unicode?



> Windows doesn't have unicode?

Windows do have unicodes. The problem with the installation is that readme.md file contains some illegal character which are not understandable for python interpreter when its tries to read readme.md file.

**Comment by ghost** [comment]
Same error in wsl 2 ubuntu 20.4

**Comment by BrianZbr** [comment]
Native Ubuntu install here but `sudo pip install pdfparanoia` also fails. Here's the full output from running that command in a fresh venv environment.

```
Collecting pdfparanoia
  Using cached pdfparanoia-0.0.16.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4cjhk3fc/pdfparanoia/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4cjhk3fc/pdfparanoia/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4cjhk3fc/pdfparanoia/pip-egg-info
         cwd: /tmp/pip-install-4cjhk3fc/pdfparanoia/
    Complete output (14 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4cjhk3fc/pdfparanoia/setup.py", line 6, in <module>
        import pdfparanoia
      File "/tmp/pip-install-4cjhk3fc/pdfparanoia/pdfparanoia/__init__.py", line 27, in <module>
        from .core import scrub
      File "/tmp/pip-install-4cjhk3fc/pdfparanoia/pdfparanoia/core.py", line 20, in <module>
        from pdfparanoia.plugins import *
      File "/tmp/pip-install-4cjhk3fc/pdfparanoia/pdfparanoia/plugins/__init__.py", line 12, in <module>
        from .jstor import *
      File "/tmp/pip-install-4cjhk3fc/pdfparanoia/pdfparanoia/plugins/jstor.py", line 98
        except PDFObjectNotFound, e:
                                ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
