### ISSUE TITLE
installation error - pdfminer is installed

### ISSUE THREAD

**Issue by PinkMushroom** [kanzure/pdfparanoia#57]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a2g2qkxz/pdfparanoia/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a2g2qkxz/pdfparanoia/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-a2g2qkxz/pdfparanoia/pip-egg-info
         cwd: /tmp/pip-install-a2g2qkxz/pdfparanoia/
    Complete output (14 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a2g2qkxz/pdfparanoia/setup.py", line 6, in <module>
        import pdfparanoia
      File "/tmp/pip-install-a2g2qkxz/pdfparanoia/pdfparanoia/__init__.py", line 27, in <module>
        from .core import scrub
      File "/tmp/pip-install-a2g2qkxz/pdfparanoia/pdfparanoia/core.py", line 20, in <module>
        from pdfparanoia.plugins import *
      File "/tmp/pip-install-a2g2qkxz/pdfparanoia/pdfparanoia/plugins/__init__.py", line 12, in <module>
        from .jstor import *
      File "/tmp/pip-install-a2g2qkxz/pdfparanoia/pdfparanoia/plugins/jstor.py", line 98
        except PDFObjectNotFound, e:
                                ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

my version of pip

pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by kanzure** [comment]
I don't think this library has worked in years. You will have to do maintenance and maybe even a rewrite.
